### PR TITLE
Switch database

### PR DESCRIPTION
**Pull request by allangomessl**
switch database with same connection.

it's very useful on multi-tenant migration strategy.

```typescript
import Migrator from "ts-migrate-mongoose";

const migrator = await Migrator.connect({
  uri: "mongodb://localhost",
});

for (db of databasesToMigrate) {
  migrator.useDb(db);
  migrator.run("<COMMAND>");
}
```

### CODE REVIEW

**Comment by ilovepixelart** [comment]
I like the idea, what about props for useDb?

**Comment by allangomessl** [comment]
I chose to use Db to maintain the same pattern as Mongoose. 

in mongoose we use like this:
```typescript
connection.useDb('<dbname>')
```

but if you prefer like this, I can change.

**Comment by allangomessl** [comment]
and we can capture current connection on migration funcions

```typescript
import type { Connection } from 'mongoose'

interface IMigrationModule {
  up?: (connection: Connection) => Promise<void>
  down?: (connection: Connection) => Promise<void>
}
```

**Comment by ilovepixelart** [comment]
Style is good, but useDb has second parameter https://mongoosejs.com/docs/api/connection.html#Connection.prototype.useDb()

**Comment by allangomessl** [comment]
Hmm, true! I'm going to change that.

**Comment by allangomessl** [comment]
done.

```typescript
const databases = ["customer-1", "customer-2"]

for (const db of databases) {
  migrator.useDb(db);
  await migrator.run("up");
  await migrator.sync();
}
await migrator.close()
```
<br />

`1689439856619-my-migration-name.ts`
```typescript
// Import your models here

import { Connection } from "mongoose";

export async function up (connection: Connection): Promise<void> {
  console.log('current database is: ', connection.db.databaseName)
}

export async function down (): Promise<void> {
  // Write migration here
}

```
<br />

`output`
```sh
current database is: customer-1
current database is: customer-2
```

to capture current connection, I'm passing connection as parameter to migration functions
we can see a similar design on https://www.npmjs.com/package/migrate-mongo

**Comment by allangomessl** [comment]
Could you kindly explain the reasons behind the closure of this Pull Request? 
I am looking forward to understanding your perspective to improve future submissions.

**Comment by ilovepixelart** [comment]
Two weeks without activity, I made some comments, check them out we can discuss further

**Comment by yerycs** [comment]
@ilovepixelart Could you implement this feature if possible?

**Comment by ilovepixelart** [comment]
Hey @yerycs you have access to connection migrator.connection.useDb('mydb');
Just make an iteration
https://mongoosejs.com/docs/api/connection.html#Connection.prototype.useDb()

**Comment by yerycs** [comment]
Hi @ilovepixelart. I need to access connection info in up, down functions for each migration files.
How can I access?

**Pull request closed without merging**
