### PR TITLE
fix/commander-migrator-priorities

### PR DESCRIPTION
**Pull request by mkloouo**
I was trying to use `.env` and failed miserably :)

### CODE REVIEW

**Comment by ilovepixelart** [comment]
@mkloouo hey thanks for the pr)
I want to understand the issue you having with the priorities, if you running migrations using command line interface why .env should have priority over user args (isn't it defeating the point of user entering command args in the first place). I would like to know what is your specific scenario.

**Comment by mkloouo** [comment]
> @mkloouo hey thanks for the pr)
> 
> I want to understand the issue you having with the priorities, if you running migrations using command line interface why .env should have priority over user args (isn't it defeating the point of user entering command args in the first place). I would like to know what is your specific scenario.
> 
> 
> 
> In case you using programmatic approach (I see the point) but even then why not:
> 
> 
> 
> ```typescript
> 
> import Migrator from 'ts-migrate-mongoose'
> 
> 
> 
> const migrator = new Migrator({
> 
>   uri: process.env.MIGRATE_MONGO_URI,
> 
>   collection: 'migrations', 
> 
>   migrationsPath:  '/path/to/migrations/',
> 
>   templatePath: '/path/to/template.ts',
> 
>   autosync: true
> 
> })
> 
> 
> 
> await migrator.run('up')
> 
> ```
> 
> 
> 
> https://github.com/ilovepixelart/ts-migrate-mongoose#options-override-order

You're right, I stumbled upon that when using with cmdline interface. 

I agree with you on matter of cmdline over env, but. There is an issue with cmdline being defaulted, but package does not check if there are env passed, thus uses default ones.

**Comment by ilovepixelart** [comment]
Alright now I get your point, then we need to change the approach a bit for default values in `Migrate` class, and there is no need to change an order in `getMigrator`

**Comment by ilovepixelart** [comment]
https://github.com/ilovepixelart/ts-migrate-mongoose/pull/56 ok lets proceed with this

**Pull request closed without merging**
